using CppAst;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace EmbreeGen
{
	public class CsCodeGenerator
	{
		private const string Namespace = "Evergine.Bindings.Embree";
		private const string NativeClass = "Embree";
		private const string LibraryName = "embree4";

		/// <summary>
		/// Functions declared RTC_FORCEINLINE in the headers. They are compiled into the caller,
		/// so the shared library exports no symbol for them. Hand-written equivalents live in
		/// Evergine.Bindings.Embree/Embree.Inline.cs.
		/// </summary>
		private static readonly HashSet<string> InlineOnlyFunctions = new HashSet<string>
		{
			"rtcInitRayQueryContext",
			"rtcInitPointQueryContext",
			"rtcInitIntersectArguments",
			"rtcInitOccludedArguments",
			"rtcDefaultBuildArguments",
			"rtcInitQuaternionDecomposition",
			"rtcQuaternionDecompositionSetQuaternion",
			"rtcQuaternionDecompositionSetScale",
			"rtcQuaternionDecompositionSetSkew",
			"rtcQuaternionDecompositionSetShift",
			"rtcQuaternionDecompositionSetTranslation",
			"rtcInterpolate0",
			"rtcInterpolate1",
			"rtcInterpolate2",
		};

		/// <summary>
		/// Embree does not use the "&lt;EnumName&gt;Flags" typedef convention, so bit-flag enums are listed here.
		/// </summary>
		private static readonly HashSet<string> FlagEnums = new HashSet<string>
		{
			"RTCFeatureFlags",
			"RTCRayQueryFlags",
			"RTCSceneFlags",
			"RTCBuildFlags",
			"RTCCurveFlags",
		};

		/// <summary>
		/// Macros worth exposing, with the C# type to emit and an optional value override for
		/// expressions the C# compiler cannot parse (casts, macro indirection).
		/// </summary>
		private static readonly Dictionary<string, (string Type, string Value)> ExportedMacros =
			new Dictionary<string, (string, string)>
		{
			{ "RTC_VERSION_MAJOR",            ("uint",   null) },
			{ "RTC_VERSION_MINOR",            ("uint",   null) },
			{ "RTC_VERSION_PATCH",            ("uint",   null) },
			{ "RTC_VERSION",                  ("uint",   null) },
			{ "RTC_VERSION_STRING",           ("string", null) },
			{ "RTC_MAX_INSTANCE_LEVEL_COUNT", ("uint",   null) },
			{ "RTC_MAX_TIME_STEP_COUNT",      ("uint",   null) },
			{ "RTC_MIN_WIDTH",                ("uint",   "0") },              // expands to EMBREE_MIN_WIDTH
			{ "RTC_INVALID_GEOMETRY_ID",      ("uint",   "uint.MaxValue") },  // ((unsigned int)-1)
		};

		private CsCodeGenerator()
		{
		}

		public static CsCodeGenerator Instance { get; } = new CsCodeGenerator();

		public void Generate(CppCompilation compilation, string outputPath)
		{
			CollectTypedefs(compilation);
			CollectOpaqueStructs(compilation);

			GenerateConstants(compilation, outputPath);
			GenerateEnums(compilation, outputPath);
			GenerateDelegates(compilation, outputPath);
			GenerateHandles(compilation, outputPath);
			GenerateStructs(compilation, outputPath);
			GenerateFunctions(compilation, outputPath);
		}

		private static void CollectTypedefs(CppCompilation compilation)
		{
			Helpers.HandleTypedefs.Clear();
			Helpers.FunctionPointerTypedefs.Clear();

			foreach (var typedef in compilation.Typedefs)
			{
				if (typedef.ElementType is not CppPointerType pointer)
					continue;

				var pointee = pointer.ElementType;
				if (pointee is CppQualifiedType qualified)
					pointee = qualified.ElementType;

				if (pointee is CppFunctionType functionType)
				{
					Helpers.FunctionPointerTypedefs[typedef.Name] = functionType;
				}
				else
				{
					Helpers.HandleTypedefs.Add(typedef.Name);
				}
			}
		}

		private static void CollectOpaqueStructs(CppCompilation compilation)
		{
			Helpers.OpaqueStructs.Clear();

			var defined = new HashSet<string>(
				compilation.Classes.Where(c => c.IsDefinition).Select(c => c.Name));

			foreach (var @class in compilation.Classes.Where(c => !c.IsDefinition))
			{
				if (!defined.Contains(@class.Name))
					Helpers.OpaqueStructs.Add(@class.Name);
			}
		}

		private static void WriteHeader(StreamWriter file, params string[] usings)
		{
			file.WriteLine("// <auto-generated />");
			file.WriteLine("// Generated by EmbreeGen from the Embree 4 public headers. Do not edit by hand.");
			file.WriteLine();
			foreach (var @using in usings)
			{
				file.WriteLine($"using {@using};");
			}
			file.WriteLine();
			file.WriteLine($"namespace {Namespace}");
			file.WriteLine("{");
		}

		private void GenerateConstants(CppCompilation compilation, string outputPath)
		{
			Console.WriteLine("Generating Constants...");

			using var file = File.CreateText(Path.Combine(outputPath, "Constants.cs"));
			WriteHeader(file, "System");
			file.WriteLine($"\tpublic static partial class {NativeClass}");
			file.WriteLine("\t{");

			var macrosByName = compilation.Macros
				.GroupBy(m => m.Name)
				.ToDictionary(g => g.Key, g => g.Last());

			foreach (var pair in ExportedMacros)
			{
				if (!macrosByName.TryGetValue(pair.Key, out var macro))
				{
					Console.WriteLine($"  WARNING: expected macro {pair.Key} not found in the headers.");
					continue;
				}

				string csName = Helpers.StripPrefix(macro.Name);
				string value = pair.Value.Value ?? macro.Value;
				file.WriteLine($"\t\tpublic const {pair.Value.Type} {csName} = {value};");
			}

			file.WriteLine("\t}");
			file.WriteLine("}");
		}

		private void GenerateEnums(CppCompilation compilation, string outputPath)
		{
			Console.WriteLine("Generating Enums...");

			using var file = File.CreateText(Path.Combine(outputPath, "Enums.cs"));
			WriteHeader(file, "System");

			var enums = compilation.Enums.Where(e => e.Items.Count > 0 && !e.IsAnonymous).ToList();

			foreach (var cppEnum in enums)
			{
				Helpers.PrintComments(file, cppEnum.Comment, "\t");

				if (FlagEnums.Contains(cppEnum.Name))
					file.WriteLine("\t[Flags]");

				// A C enum widens to unsigned int as soon as one of its values does not fit in an
				// int (RTC_FEATURE_FLAG_ALL = 0xffffffff), but CppAst reports both the integer type
				// and that value sign-extended. A bit-mask enum that ended up with a negative value
				// is therefore really unsigned, and both the base type and the printed values have
				// to follow.
				bool isFlags = FlagEnums.Contains(cppEnum.Name);
				bool needsUnsigned = IsUnsignedEnum(cppEnum)
					|| (isFlags && cppEnum.Items.Any(i => i.Value < 0));
				string baseType = needsUnsigned ? " : uint" : string.Empty;

				string csEnumName = Helpers.StripPrefix(cppEnum.Name);
				file.WriteLine($"\tpublic enum {csEnumName}{baseType}");
				file.WriteLine("\t{");

				string commonPrefix = Helpers.FindCommonPrefix(cppEnum.Items.Select(i => i.Name));

				foreach (var member in cppEnum.Items)
				{
					Helpers.PrintComments(file, member.Comment, "\t\t", true);

					string valueName = member.Name;
					if (commonPrefix.Length > 0 && valueName.StartsWith(commonPrefix, StringComparison.Ordinal))
						valueName = valueName.Substring(commonPrefix.Length);
					else
						valueName = Helpers.StripPrefix(valueName);

					valueName = Helpers.EscapeReservedKeyword(Helpers.ScreamingToPascalCase(valueName));

					string value = needsUnsigned
						? unchecked((uint)member.Value).ToString() + "u"
						: member.Value.ToString();

					file.WriteLine($"\t\t{valueName} = {value},");
				}

				file.WriteLine("\t}");
				file.WriteLine();
			}

			file.WriteLine("}");
		}

		private static bool IsUnsignedEnum(CppEnum cppEnum)
		{
			if (cppEnum.IntegerType is CppPrimitiveType primitive)
			{
				switch (primitive.Kind)
				{
					case CppPrimitiveKind.UnsignedInt:
					case CppPrimitiveKind.UnsignedLong:
					case CppPrimitiveKind.UnsignedLongLong:
					case CppPrimitiveKind.UnsignedShort:
					case CppPrimitiveKind.UnsignedChar:
						return true;
				}
			}

			return cppEnum.Items.Any(i => i.Value > int.MaxValue);
		}

		private void GenerateDelegates(CppCompilation compilation, string outputPath)
		{
			Console.WriteLine("Generating Delegates...");

			using var file = File.CreateText(Path.Combine(outputPath, "Delegates.cs"));
			WriteHeader(file, "System", "System.Runtime.InteropServices");

			var emitted = new HashSet<string>();

			foreach (var typedef in compilation.Typedefs)
			{
				if (!Helpers.FunctionPointerTypedefs.TryGetValue(typedef.Name, out var functionType))
					continue;

				string csName = Helpers.StripPrefix(typedef.Name);
				if (!emitted.Add(csName))
					continue;

				Helpers.PrintComments(file, typedef.Comment, "\t");
				file.WriteLine("\t[UnmanagedFunctionPointer(CallingConvention.Cdecl)]");

				string returnType = Helpers.ConvertToCSharpType(functionType.ReturnType);
				file.Write($"\tpublic unsafe delegate {returnType} {csName}(");

				for (int i = 0; i < functionType.Parameters.Count; i++)
				{
					if (i > 0) file.Write(", ");
					var parameter = functionType.Parameters[i];
					string type = Helpers.ConvertToCSharpType(parameter.Type);
					string name = Helpers.EscapeReservedKeyword(
						string.IsNullOrEmpty(parameter.Name) ? $"arg{i}" : parameter.Name);
					file.Write($"{type} {name}");
				}

				file.WriteLine(");");
				file.WriteLine();
			}

			file.WriteLine("}");
		}

		private void GenerateHandles(CppCompilation compilation, string outputPath)
		{
			Console.WriteLine("Generating Handles...");

			using var file = File.CreateText(Path.Combine(outputPath, "Handles.cs"));
			WriteHeader(file, "System");

			var emitted = new HashSet<string>();

			foreach (var typedef in compilation.Typedefs)
			{
				if (!Helpers.HandleTypedefs.Contains(typedef.Name))
					continue;

				string csName = Helpers.StripPrefix(typedef.Name);
				if (!emitted.Add(csName))
					continue;

				Helpers.PrintComments(file, typedef.Comment, "\t");
				file.WriteLine($"\tpublic partial struct {csName} : IEquatable<{csName}>");
				file.WriteLine("\t{");
				file.WriteLine("\t\tpublic readonly IntPtr Handle;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic {csName}(IntPtr existingHandle) => this.Handle = existingHandle;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic static {csName} Null => new {csName}(IntPtr.Zero);");
				file.WriteLine();
				file.WriteLine("\t\tpublic bool IsNull => this.Handle == IntPtr.Zero;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic static implicit operator {csName}(IntPtr handle) => new {csName}(handle);");
				file.WriteLine();
				file.WriteLine($"\t\tpublic static implicit operator IntPtr({csName} handle) => handle.Handle;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic static bool operator ==({csName} left, {csName} right) => left.Handle == right.Handle;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic static bool operator !=({csName} left, {csName} right) => left.Handle != right.Handle;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic bool Equals({csName} other) => this.Handle == other.Handle;");
				file.WriteLine();
				file.WriteLine($"\t\tpublic override bool Equals(object obj) => obj is {csName} other && this.Equals(other);");
				file.WriteLine();
				file.WriteLine("\t\tpublic override int GetHashCode() => this.Handle.GetHashCode();");
				file.WriteLine();
				file.WriteLine($"\t\tpublic override string ToString() => $\"{csName}(0x{{this.Handle.ToInt64():X}})\";");
				file.WriteLine("\t}");
				file.WriteLine();
			}

			file.WriteLine("}");
		}

		private void GenerateStructs(CppCompilation compilation, string outputPath)
		{
			Console.WriteLine("Generating Structs...");

			using var file = File.CreateText(Path.Combine(outputPath, "Structs.cs"));
			WriteHeader(file, "System", "System.Runtime.InteropServices");

			var structs = compilation.Classes
				.Where(c => c.IsDefinition
						 && (c.ClassKind == CppClassKind.Struct || c.ClassKind == CppClassKind.Union)
						 && !c.IsAnonymous
						 && !string.IsNullOrEmpty(c.Name));

			foreach (var structure in structs)
			{
				Helpers.PrintComments(file, structure.Comment, "\t");

				bool isUnion = structure.ClassKind == CppClassKind.Union;
				string layout = isUnion ? "LayoutKind.Explicit" : "LayoutKind.Sequential";

				// Most Embree structs are declared RTC_ALIGN(16/32/64), which rounds their C sizeof
				// up to a multiple of the alignment (RTCHit is 36 bytes of fields but 48 bytes wide).
				// A plain sequential C# struct would be narrower, so RTCRayHit and every array of
				// these types would be laid out wrong. Emit the size clang computed instead.
				string size = structure.SizeOf > 0 ? $", Size = {structure.SizeOf}" : string.Empty;

				file.WriteLine($"\t[StructLayout({layout}{size})]");

				string csStructName = Helpers.StripPrefix(structure.Name);
				if (structure.AlignOf > 0)
				{
					file.WriteLine($"\t// C alignment: {structure.AlignOf} bytes.");
				}

				file.WriteLine($"\tpublic unsafe struct {csStructName}");
				file.WriteLine("\t{");

				foreach (var member in structure.Fields)
				{
					Helpers.PrintComments(file, member.Comment, "\t\t", true);

					string fieldName = Helpers.EscapeReservedKeyword(Helpers.PascalCaseField(member.Name));
					string prefix = isUnion ? "\t\t[FieldOffset(0)] " : "\t\t";

					if (member.Type is CppArrayType arrayType)
					{
						int count = Helpers.GetFlattenedArraySize(arrayType, out var elementType);
						string elementCsType = Helpers.ShowAsMarshalType(
							Helpers.ConvertToCSharpType(elementType), Helpers.Family.field);

						if (Helpers.CanBeFixedBuffer(elementCsType))
						{
							file.WriteLine($"{prefix}public fixed {elementCsType} {fieldName}[{count}];");
						}
						else
						{
							// fixed buffers only support primitives; expand into individual fields.
							for (int i = 0; i < count; i++)
							{
								file.WriteLine($"{prefix}public {elementCsType} {fieldName}{i};");
							}
						}

						continue;
					}

					string type = Helpers.ShowAsMarshalType(
						Helpers.ConvertToCSharpType(member.Type), Helpers.Family.field);
					file.WriteLine($"{prefix}public {type} {fieldName};");
				}

				file.WriteLine("\t}");
				file.WriteLine();
			}

			file.WriteLine("}");
		}

		private void GenerateFunctions(CppCompilation compilation, string outputPath)
		{
			Console.WriteLine("Generating Functions...");

			using var file = File.CreateText(Path.Combine(outputPath, "Functions.cs"));
			WriteHeader(file, "System", "System.Runtime.InteropServices");
			file.WriteLine($"\tpublic static unsafe partial class {NativeClass}");
			file.WriteLine("\t{");

			int count = 0;
			var emitted = new HashSet<string>();

			foreach (var cppFunction in compilation.Functions)
			{
				if ((cppFunction.Flags & CppFunctionFlags.FunctionTemplate) != CppFunctionFlags.None) continue;
				if ((cppFunction.Flags & CppFunctionFlags.Inline) != CppFunctionFlags.None) continue;
				if (InlineOnlyFunctions.Contains(cppFunction.Name)) continue;
				if (!emitted.Add(cppFunction.Name)) continue;

				string originalName = cppFunction.Name;
				string csName = Helpers.StripPrefix(originalName);
				csName = char.ToUpperInvariant(csName[0]) + csName.Substring(1);

				Helpers.PrintComments(file, cppFunction.Comment, "\t\t");
				file.WriteLine($"\t\t[DllImport(\"{LibraryName}\", EntryPoint = \"{originalName}\", CallingConvention = CallingConvention.Cdecl)]");

				string returnType = Helpers.ShowAsMarshalType(
					Helpers.ConvertToCSharpType(cppFunction.ReturnType), Helpers.Family.ret);

				file.Write($"\t\tpublic static extern {returnType} {csName}(");

				for (int i = 0; i < cppFunction.Parameters.Count; i++)
				{
					if (i > 0) file.Write(", ");
					var parameter = cppFunction.Parameters[i];
					string type = Helpers.ShowAsMarshalType(
						Helpers.ConvertToCSharpType(parameter.Type), Helpers.Family.param);
					string name = Helpers.EscapeReservedKeyword(
						string.IsNullOrEmpty(parameter.Name) ? $"arg{i}" : parameter.Name);
					file.Write($"{type} {name}");
				}

				file.WriteLine(");");
				file.WriteLine();
				count++;
			}

			file.WriteLine("\t}");
			file.WriteLine("}");

			Console.WriteLine($"  {count} functions generated.");
		}
	}
}
